(define (maxpot b n k) (if (not (>= n (expt b k))) (sub1 k) (maxpot b n (add1 k))))
(define b 0)
(define n 0)
(display "Ora sarà calcolata la massima potenza per b^k <= n\n")
(display "Inserisci ora b: ")
(set! b (read))
(display "Inserisci ora n: ")
(set! n (read))
(if (and (> b 1) (> n 0))
    (string-append "La massima potenza che soddisfa b^k <= n e': " (number->string (maxpot b n 0)))
    (quote "E' subentrato un errore: devi aver imposto b<=1 e/o n<=0\n"))
